internal:
    clients:
        mockservice1:
            secret: "somesecret"
            scopes:
                - SCOPE_SEND_INFORMATION
                - SCOPE_REGISTER
    oauth:
        server:
            issuer: argos


