spring:
    graphql:
        http:
            path: /graphql
    mongodb:
        uri: mongodb://localhost:27017/argos?maxPoolSize=50&minPoolSize=5&maxIdleTimeMS=300000&socketTimeoutMS=10000&connectTimeoutMS=5000&serverSelectionTimeoutMS=5000&retryWrites=true
        auto-index-creation: true

server:
    port: 8080

internal:
    oauth:
        server:
            issuer: argos
            audience: argos-internal
        clients:
            mockservice1:
                secret: somesecret
                scopes:
                    - SCOPE_SEND_INFORMATION
