spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/argos?maxPoolSize=50&minPoolSize=5&maxIdleTimeMS=300000&socketTimeoutMS=10000&connectTimeoutMS=5000&serverSelectionTimeoutMS=5000&retryWrites=true
      database: argos
      auto-index-creation: true

  graphql:
    path: /graphql
    schema:
      locations: classpath:graphql/

server:
  port: 8080
